# Esta es la imagen del repositorio php, versión 7.2 con apache
# a partir de esta imagen de base, creamos nuestra imagen personalizada
FROM php:7.2-apache

# Copiamos el contenido del subdirectorio ./data (de nuestro equipo)
# al directorio raíz del servidor apache, dentro de la imagen
COPY data/ /var/www/html/
