# docker-tutorial
# docker-compose -f docker-compose.yml up

version: "3.1"
networks:
  tutorialnet:
services:
  h2-bdd:
    image: daoc/h2
    ports:
      - 8082:8082
    volumes:
      - ~/git/Docker/docker-tutorial/intermedio01/vol:/home/h2/data
    networks:
      - tutorialnet
  backend:
    image: daoc/rest-backend
    networks:
      - tutorialnet
  frontend:
    image: daoc/web-frontend
    ports:
      - 80:80
    networks:
      - tutorialnet

