# docker-tutorial

# En el node manager:
# docker stack deploy -c docker-compose.yml my_web

version: "3.1"
networks:
  tutorialnet:
services:
  h2-bdd:
    image: daoc/h2
    ports:
      - 8082:8082
    volumes:
      - ~/Home/Github/ApDist/docker-tutorial/srvcs01/vol:/home/h2/data
      # - ~/git/Docker/docker-tutorial/intermedio01/vol:/home/h2/data
    deploy:
        replicas: 1 # Tiene que ser 1, dado que debe haber una bdd central
    networks:
      - tutorialnet
  backend:
    image: daoc/rest-backend
    deploy:
        replicas: 2 # No importa mucho para el ejemplo
    networks:
      - tutorialnet
  frontend:
    image: daoc/web-frontend
    ports:
      - 80:80
    deploy:
        replicas: 3 # dependiendo del número de nodos, 1 por nodo, pero puede variar (más o menos copias)
    networks:
      - tutorialnet

